.RADIX 16

FLAG0_DISABLE_INTRO				textequ <01>
FLAG0_HIDE_ALL_UI				textequ <10>
FLAG0_HIDE_SUBPALETTE			textequ <20>
FLAG0_HIDE_SCREEN_NOTIFICATIONS	textequ	<40>
FLAG0_HIDE_ECODES				textequ <80>

FLAG1_DISABLE_NEAR_CULLING		textequ <01>
FLAG1_DISABLE_FAR_CULLING		textequ <02>
FLAG1_DISABLE_UPDATE_CULLING	textequ <04>
FLAG1_DISABLE_LOD_REDUCTION		textequ <08>
FLAG1_OVERRIDE_NORMAL_CAMERA	textequ <10>
FLAG1_OVERRIDE_SHOOTER_CAMERA	textequ <20>